import Head from "next/head";

import { Inter } from "@next/font/google";

import React from "react";

import dynamic from "next/dynamic";
import { useRouter } from "next/router";

const WEditorContainer = dynamic(
  () => import("@src/blog_component/_containers/WEditorContainer"),
  {
    ssr: false,
  }
);

const inter = Inter({ subsets: ["latin"] });

export default function Editor() {
  const router = useRouter();

  const { redirect } = router.query;

  return (
    <>
      <Head>
        <title>XCC629 | Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <WEditorContainer />
      </div>
    </>
  );
}
