import Head from "next/head";

import { Inter } from "@next/font/google";
import Typograpy from "../../src/common_component/Typograpy";
import Input from "../../src/blog_component/_component/Input";
import Button from "../../src/common_component/Button";

import Div from "../../src/common_component/Div";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  return (
    <>
      <Head>
        <title>XCC629 | LOGIN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ padding: "100px" }}>
        <Div>
          <Typograpy>아이디</Typograpy>
          <Input type="email" />
        </Div>
        <Div padding="20px 0 30px">
          <Typograpy>비밀번호</Typograpy>
          <Input type="password" />
        </Div>
        <Div>
          <Button
            size={340}
            height="50px"
            color="white"
            backgroundColor="green300"
            borderRadius="8px"
            onClick={() => console.log("dd")}
          >
            로그인하기
          </Button>
        </Div>
      </div>
    </>
  );
}
