import SeriesContainer from "@src/blog_component/_containers/SeriesContainer";

import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import getSeries from "pages/api/getSeries";

export default function Series({
  param,
  seriesInfo,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>XCC629 | SERIES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SeriesContainer param={param} seriesInfo={seriesInfo} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({
  query: { id },
}) => {
  const seriesInfo = await getSeries(id as string);

  return {
    props: {
      seriesInfo: seriesInfo,
      param: id,
    },
  };
};
