import * as React from "react";

import Head from "next/head";
import { useRouter } from "next/router";

import PostContainer from "../../src/blog_component/_containers/PostContainer";

export default function Post() {
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>XCC629</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostContainer />
    </>
  );
}
