import Head from "next/head";

import { Inter } from "@next/font/google";
import HomeContainer from "@src/blog_component/_containers/HomeContainer";

const inter = Inter({ subsets: ["latin"] });

export default function Tech() {
  return (
    <>
      <Head>
        <title>XCC629 | TECH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContainer />
    </>
  );
}
