import Head from "next/head";

import { Inter } from "@next/font/google";
import WEditorContainer from "../../src/blog_component/_containers/WEditorContainer";
import WEHeader from "../../src/blog_component/_component/WEHeader";

const inter = Inter({ subsets: ["latin"] });

export default function Editor() {
  return (
    <>
      <Head>
        <title>XCC629 | Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <WEditorContainer />
      </div>
    </>
  );
}
