import Head from "next/head";

import React from "react";

import { Inter } from "@next/font/google";
import Typograpy from "../src/common_component/Typograpy";
import Div from "../src/common_component/Div";
import Link from "next/link";
import { HREF } from "../src/libs/const";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>XCC629 | HOME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ padding: "100px 0" }}>
        <Typograpy size={30}>안녕하세요.</Typograpy>
        <Typograpy>프론트엔드 개발자 임근홍</Typograpy>
        <Typograpy size={30}>개인 블로그입니다.</Typograpy>

        <Div margin="20px 0 0">
          <Link href={HREF.tech}>
            <Div backgroundColor="green300">
              <Typograpy color="white" padding="10px">
                go: 기술 블로그
              </Typograpy>
            </Div>
          </Link>
          <Link href={HREF.resume}>
            <Div backgroundColor="green300" margin="5px 0 0">
              <Typograpy color="white" padding="10px">
                go: 이력서와 포트폴리오
              </Typograpy>
            </Div>
          </Link>
        </Div>
      </div>
    </>
  );
}
