import Head from "next/head";

import { Inter } from "@next/font/google";

import React from "react";

import dynamic from "next/dynamic";
import getSeriesAllList from "pages/api/getSeriesAllList";

const WEditorContainer = dynamic(() => import("app/edit/WEditorContainer"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export async function getData() {
  const res = await getSeriesAllList();
  return res;
}

export default async function Page() {
  const seriesAllListData = getData();

  const [seriesAllList] = await Promise.all([seriesAllListData]);

  return (
    <>
      <Head>
        <title>XCC629 | Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WEditorContainer seriesAllList={seriesAllList} />
    </>
  );
}
