import SeriesContainer from "app/series/SeriesContainer";

import Head from "next/head";
import getSeries from "pages/api/getSeries";

export interface IParamProps {
  params: {
    id: string;
  };
}

export async function getData(id: string) {
  const res = await getSeries(id);
  return res;
}

export default async function Page({ params }: IParamProps) {
  const id = params.id;
  const seriesInfoData = getData(id);

  const [seriesInfo] = await Promise.all([seriesInfoData]);

  return (
    <>
      <Head>
        <title>XCC629 | SERIES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SeriesContainer param={id} seriesInfo={seriesInfo} />
    </>
  );
}
