import * as React from "react";

import Head from "next/head";

import PostContainer from "app/post/PostContainer";
import { GetStaticPaths, GetStaticProps, InferGetStaticPropsType } from "next";
import getPost from "pages/api/getPost";
import getPostIdList from "pages/api/getPostIdList";
import prisma from "@src/libs/prisma";

export const revalidate = 60;

export async function getData(id: string) {
  try {
    const data = await prisma.post.findUnique({
      where: {
        id: Number(id),
      },
      select: {
        id: true,
        createdAt: true,
        title: true,
        published: true,
        content: true,
        series: {
          select: {
            id: true,
            title: true,
          },
        },
      },
    });

    const res = JSON.parse(JSON.stringify(data));
    return res;
  } catch (err) {
    console.log(err);
  }
}

export interface IParamProps {
  params: {
    id: string;
  };
}

export default async function Page({ params }: IParamProps) {
  const id = params.id;
  const postData = getData(id);
  const [post] = await Promise.all([postData]);

  return (
    <>
      <Head>
        <title>XCC629 | POST</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostContainer post={post} />
    </>
  );
}
